### ISSUE TITLE
Seitenanalyse, Crawling+DB, Visualisierungen

### ISSUE THREAD

**Issue by enplotz** [enplotz/webir2015#1]
![scanbot 19 nov 2015 11 46](https://cloud.githubusercontent.com/assets/949068/11268887/b8df1c72-8eb3-11e5-8b29-88f423c32a57.jpg)

**Comment by raffaelwagner** [comment]
![image](https://cloud.githubusercontent.com/assets/7667071/11268775/fce5d2c2-8eb2-11e5-955e-1ca65f1d38e6.jpeg)

**Comment by raffaelwagner** [comment]
[Scanbot 19 Nov 2015 11.46.pdf](https://github.com/enplotz/webir2015/files/38831/Scanbot.19.Nov.2015.11.46.pdf)

**Comment by enplotz** [comment]
Danke @raffaelwagner!

**Comment by ghost** [comment]
User-IDs enden ganz selten nicht mit AAAJ, bei Pattern Matching also beachten...
