### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by enplotz** [enplotz/webir2015#5]
- [x] postgres 9.4
- [x] Tabellen ausdenken

**Comment by enplotz** [comment]
![image](https://cloud.githubusercontent.com/assets/949068/11531366/a3531a4a-98fc-11e5-8ef7-2cd63434397c.jpeg)

**Comment by ghost** [comment]
[dump.txt](https://github.com/enplotz/webir2015/files/50430/dump.txt)
